export const sampleStandings = [
  {
    entry_id: "auto_11237_01",
    rank: 1,
    name: "Vega Mobile Auto",
    league: "Auto",
    neighborhood: "Bushwick",
    zip_code: "11237",
    score: 94,
    rating: 4.9,
    distance_miles: 0.8,
    status: "active",
  },
  {
    entry_id: "auto_11237_02",
    rank: 2,
    name: "RoadReady NYC",
    league: "Auto",
    neighborhood: "Bushwick",
    zip_code: "11237",
    score: 91,
    rating: 4.8,
    distance_miles: 1.1,
    status: "active",
  },
  {
    entry_id: "auto_11237_03",
    rank: 3,
    name: "Brooklyn Bay Garage",
    league: "Auto",
    neighborhood: "Bushwick",
    zip_code: "11237",
    score: 88,
    rating: 4.8,
    distance_miles: 1.4,
    status: "active",
  },
  {
    entry_id: "auto_11237_04",
    rank: 4,
    name: "Torres Auto Works",
    league: "Auto",
    neighborhood: "Bushwick",
    zip_code: "11237",
    score: 85,
    rating: 4.7,
    distance_miles: 0.6,
    status: "active",
  },
];
